spring.application.name: spring-ai-local

spring:
  ai:
    ollama:
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            - mxbai-embed-large
            - nomic-embed-text
      chat:
        options:
          model: llama3.1:8b
      embedding:
        options:
          model:
            hf.co/mixedbread-ai/mxbai-embed-large-v1
    openai:
      api-key: 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
    vertex:
      ai:
        gemini:
          project-id: ai-circle-2025-cluster-34390
          location: europe-north1
#          credentials-uri:
#          api-endpoint: https://gemini.googleapis.com/v1/models/
  http:
    client:
      factory: jdk
