spring.application.name: spring-ai-local

spring:
  ai:
    ollama:
      init:
        pull-model-strategy: always
        embedding:
          options:
            model:
              hf.co/mixedbread-ai/mxbai-embed-large-v1
          additional-models:
            - mxbai-embed-large
            - nomic-embed-text
      chat:
        options:
          model: llama3.1:8b
  http:
    client:
      factory: jdk
