spring.application.name: spring-ai-local

spring:
  ai:
    ollama:
#      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b
  http:
    client:
      factory: jdk
